[client]
toolbarMode = "viewer" # Geliştirici araç çubuğunu gizle

[theme]
primaryColor = "#7928CA" # Senin mor rengin
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#31333F"
font = "sans serif"

[server]
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false # Streamlit'e veri göndermeyi kapat
